#!/bin/bash

set -euo pipefail

read -r bazel_version<.bazelversion
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    readonly bazel_platform="linux"
    readonly bazel_version_sha="6c25a6d716545d6b672ec46f770521cd9ebb63d73617b8f4e6747825d1db1839"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    readonly bazel_platform="darwin"
    readonly bazel_version_sha="74d93848f0c9d592e341e48341c53c87e3cb304a54a2a1ee9cff3df422f0b23c"
else
    >&2 echo "error: unhandled OSTYPE $OSTYPE"
    exit 1
fi

echo "using bazel@${bazel_version} for ${bazel_platform}"

readonly bazel_version_url="https://github.com/bazelbuild/bazel/releases/download/$bazel_version/bazel-$bazel_version-$bazel_platform-x86_64"
readonly script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly bazel_root="$script_root/out/bazel/versions/$bazel_version-$bazel_platform"
readonly bazel_executable="$bazel_root/bin/bazel"

if [[ ! -x "$bazel_executable" ]]; then
  echo "could not find a cached installation, downloading bazel..." >&2
  mkdir -p "$(dirname "$bazel_executable")"
  extra_curl_args=""
  if [[ -n "${BUILD_BUILDID:-}" ]]; then
    extra_curl_args="--silent"
  fi

  curl \
    --show-error \
    $extra_curl_args \
    --progress-bar \
    --retry 3 \
    --fail \
    --location \
    --output "$bazel_executable" \
    "$bazel_version_url"

  if echo "$bazel_version_sha  $bazel_executable" | shasum --check --status; then
    chmod +x "$bazel_executable"
  else
    echo "Bazel installer sha mismatch:" >&2
    shasum -a256 $bazel_executable | awk '{print $1;}' >&2
    rm -f "$bazel_executable"
    exit 1
  fi
fi

exec "$bazel_executable" "$@"
